# in _config.yml
title: "Open Hardware Academy"
logo: img/jpg/logo.jpg
author: Open Hardware Academy
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [ /images/**.*,./**/*.py, ./**/*.jpg, LICENSE.md ]

# Information about where the book exists on the web
repository:
  url  : https://github.com/delftopenhardware/openhardware.academy
  branch: master
  path_to_book: docs

html:
  # announcement: "My announcement!"
  use_repository_button: true
  comments:
    utterances:
      repo: "delftopenhardware/openhardware.academy.git" 
    
  use_edit_page_button: true

  extra_footer: |
      <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.jpg" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  
  
  
  home_page_in_navbar: true

sphinx:
    config:
      html_show_copyright: false